.PHONY += flash
STM32_CUBE_PROGRAMMER_PATH = STM32_Programmer_CLI
STM32_CUBE_PROGRAMMER_ARGS = -c port=SWD mode=UR -w $(APP_ELF)

flash:
	$(STM32_CUBE_PROGRAMMER_PATH) $(STM32_CUBE_PROGRAMMER_ARGS) --verify