SOURCE_PATHS += $(BASE_PATH)/Src


EXCLUDE_SOURCE_FILES += $(BASE_PATH)/Src/stm32h7xx_ll_lpuart.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_lpuart.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_gfxmmu.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_fmc.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_delayblock.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_adc.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_dma2d.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_flash_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_rng.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_spi.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_tim.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_i2c.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_opamp.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_rtc_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_opamp.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_cec.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_crc_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_sd.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_pwr.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_fmac.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dfsdm_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_ltdc_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_hcd.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_crs.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_utils.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_rcc.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_eth_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_mdios.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_opamp_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_smbus.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_tim.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_usart_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_iwdg.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_adc_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_sdram.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_irda.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_sai_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dcmi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_timebase_rtc_wakeup_template.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_usb.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_crc.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_swpmi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_sram.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_spdifrx.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_tim_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_cryp.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_timebase_rtc_alarm_template.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_mmc.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_i2s.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_i2c.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dts.c \
						$(BASE_PATH)/Src/Legacy/stm32h7xx_hal_eth_ex.c \
						$(BASE_PATH)/Src/Legacy/stm32h7xx_hal_eth.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_comp.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_timebase_tim_template.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_rng.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_exti.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_flash.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_cryp_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_qspi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_crc.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dma2d.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_lptim.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dma_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_rng_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dfsdm.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_fmac.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_comp.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_nand.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_cordic.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_fdcan.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_msp_template.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_rtc.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_eth.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_usart.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_sai.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_ospi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dac.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_usart.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_pcd_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_sdmmc.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_spi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_nor.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_rtc.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_ramecc.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_i2c_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_i2s_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_mdma.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_dac.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_sd_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_hash.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_pcd.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_lptim.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_mmc_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_spi_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_ltdc.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_dma.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_cordic.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_gpio.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_exti.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_swpmi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_pssi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_otfdec.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_hrtim.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dsi.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_jpeg.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_wwdg.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_hash_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_smartcard.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_mdma.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_adc.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_smbus_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_hrtim.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dma.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_dac_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_hal_smartcard_ex.c \
						$(BASE_PATH)/Src/stm32h7xx_ll_bdma.c


EXTRA_SOURCE_FILES += $(BASE_PATH)/Src/stm32h7xx_hal.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_cortex.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_hsem.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_pwr_ex.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_pwr.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_gpio.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_uart_ex.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_uart.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_rcc_ex.c \
					  $(BASE_PATH)/Src/stm32h7xx_hal_rcc.c